#!/bin/bash
#Figil written by alireza.amirsamimi@ubuntu.ir and AliReaza

convert () {
    text=$@
    out=""
    for i in $(seq 0 $((${#text} - 1))); do
        hex=$(echo "${text:$i:1}" | xxd -p)

        case "$hex" in
            "300a") #0
                out="dbb00a" #۰
            ;;
            "310a") #1
                out="dbb10a" #۱
            ;;
            "320a") #2
                out="dbb20a" #۲
            ;;
            "330a") #3
                out="dbb30a" #۳
            ;;
            "340a") #4
                out="dbb40a" #۴
            ;;
            "350a") #5
                out="dbb50a" #۵
            ;;
            "360a") #6
                out="dbb60a" #۶
            ;;
            "370a") #7
                out="dbb70a" #۷
            ;;
            "380a") #8
                out="dbb80a" #۸
            ;;
            "390a") #9
                out="dbb90a" #۹
            ;;

            "610a") #a
                out="d8b40a" #ش
            ;;
            "620a") #b
                out="d8b00a" #ذ
            ;;
            "630a") #c
                out="d8b20a" #ز
            ;;
            "640a") #d
                out="db8c0a" #ی
            ;;
            "650a") #e
                out="d8ab0a" #ث
            ;;
            "660a") #f
                out="d8a80a" #ب
            ;;
            "670a") #g
                out="d9840a" #ل
            ;;
            "680a") #h
                out="d8a70a" #ا
            ;;
            "690a") #i
                out="d9870a" #ه
            ;;
            "6a0a") #j
                out="d8aa0a" #ت
            ;;
            "6b0a") #k
                out="d9860a" #ن
            ;;
            "6c0a") #l
                out="d9850a" #م
            ;;
            "6d0a") #m
                out="d9be0a" #پ
            ;;
            "6e0a") #n
                out="d8af0a" #ن
            ;;
            "6f0a") #o
                out="d8ae0a" #خ
            ;;
            "700a") #p
                out="d8ad0a" #ح
            ;;
            "710a") #q
                out="d8b60a" #ض
            ;;
            "720a") #r
                out="d9820a" #ق
            ;;
            "730a") #s
                out="d8b30a" #س
            ;;
            "740a") #t
                out="d9810a" #ف
            ;;
            "750a") #u
                out="d8b90a" #ع
            ;;
            "760a") #v
                out="d8b10a" #ر
            ;;
            "770a") #w
                out="d8b50a" #ص
            ;;
            "780a") #x
                out="d8b70a" #ط
            ;;
            "790a") #y
                out="d8ba0a" #غ
            ;;
            "7a0a") #z
                out="d8b80a" #ظ
            ;;
            *)
                out="${hex}"
            ;;
        esac

        #out=$(echo "$out" | xxd -p -r)
        echo -ne "$out"\\r
    done
}

unhex () {
	hex=$@
        out=$(echo "$hex" | xxd -p -r)
        echo -ne "$out"\\r
}

window_pid=$(xdotool getactivewindow)
clipboard=$(xclip -o -sel clip )

#xdotool type --delay 400 --window $window_pid "$(convert $clipboard)"
xdotool type --delay 400 --window $window_pid "$(unhex $(convert $clipboard))"

exit
